### ISSUE TITLE
Show Triggers does not make triggers visible.

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1078] opened 2016-11-28 02:00 UTC
I have "Show Triggers In-game" enabled in BEE2, but triggers are not visible by default.

**Comment by LautaroL20** [comment] 2016-11-28 02:14
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/365

**Closed by LautaroL20** 2016-11-28 02:14 UTC
Labels: bug, duplicate, Stylevar
