### ISSUE TITLE
Portal 1 Beemod Door is being packed as a "Mysterious White Texture" for people who do not have bee2.4 installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1027] opened 2016-11-21 20:12 UTC
![20161121170845_1](https://cloud.githubusercontent.com/assets/12244376/20498892/b440025e-b00d-11e6-9b25-b229c24f7792.jpg)

**Comment by ZombiePwner1** [comment] 2016-11-22 00:35
This a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/1023 the door is completely the same as entry door.

**Closed by ZombiePwner1** 2016-11-22 00:35 UTC
Labels: bug, duplicate, Portal 1
