### ISSUE TITLE
[Bug] BTS coop room uses clean variant instead of BTS variant :/

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#693] opened 2016-08-15 10:01 UTC

**Comment by LautaroL20** [comment] 2016-08-15 10:18
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/342

**Comment by ZombiePwner1** [comment] 2016-08-15 10:19
Lautaro come online i wanna chat :)

**Closed by LautaroL20** 2016-08-15 10:18 UTC
Labels: BTS, bug, duplicate, Missing item variant

**Comment by LautaroL20** [comment] 2016-08-15 10:19
Ok.
