### ISSUE TITLE
[Bug] Pedestal Buttons generate compile errors in old Aperture styles

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#766] opened 2016-09-04 12:42 UTC
I recently noticed that when making old Aperture style chambers, 50s, 60s, 70s and 80s, you'll get a compiler error whenever you add a Pedestal Button and connect it to anything. An unconnected button will work, but - of course - that is pretty pointless. A bit strange, considering pedestal buttons are pretty basic. In order to make an old style chamber with pedestal buttons with the latest BEE2.4 build, you have to use Lockable Pedestal Buttons instead, which still works, but looks kind of weird.

**Comment by TheDarkBomber** [comment] 2016-09-04 12:50
What does it say in the console log?

**Comment by cartman1337** [comment] 2016-09-04 12:57
How/where do I see the console log?

**Comment by cartman1337** [comment] 2016-09-04 13:03
Never mind, I think I found it.

The part with the error looks like this:
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | Could not open instance file instances/bee2/50s/items/button/pedestal_base_inf.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)


Seems like the compiler is trying to reference a file which is not there, or is there under a different name/folder.

**Comment by ZombiePwner1** [comment] 2016-09-04 13:04
Missing instance most likely

**Comment by TheDarkBomber** [comment] 2016-09-04 13:06
If that's the problem, then this is a duplicate of #701

**Comment by ZombiePwner1** [comment] 2016-09-04 13:06
it needs to be timered the infinite one is causing te error.

**Closed** 2016-09-04 13:10 UTC
Labels: bug, Missing item variant, Retro

**Comment by TheDarkBomber** [comment] 2016-09-04 13:13
This needs to be labeled duplicate.
(See #701)
