### ISSUE TITLE
Nova Prospekt style

### ISSUE THREAD

**Issue by CrashingScience** [TeamSpen210/BEE2-items#834] opened 2016-09-16 21:51 UTC
Just a quick idea I had. Not sure how/if it would work, but a nova prospect like style seen in the very early portal 1 content. Not sure if it would be possible, but could be quite interesting.

**Comment by LautaroL20** [comment] 2016-09-17 02:33
In case that there are the textures for it, then it would not be a problem, otherwise it will not be possible unless TeamSpen decided to make the textures himself.

**Comment by TheDarkBomber** [comment] 2016-09-17 07:31
Duplicate of #527

**Comment by CrashingScience** [comment] 2016-09-17 07:38
No i even earlier in dev. https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgxQhCvLcNPM_d2tgg4a48UhyGQ32pQIv9rsE4QEGLMXs_uZ0-tA

**Comment by CrashingScience** [comment] 2016-09-17 07:43
https://youtu.be/TgL1ygsDUB8

**Comment by TheDarkBomber** [comment] 2016-09-17 07:55
Can't change Portal Gun to Physics Gun.

**Comment by CrashingScience** [comment] 2016-09-17 08:28
I know that.

**Comment by TeamSpen210** [comment] 2016-09-17 09:42
At least with this most textures should be in HL2 potentially. It'm not going to be working on it any time soon though.

**Comment by ZombiePwner1** [comment] 2016-09-17 09:54
If this won't be worked on then should be closed.

**Closed** 2016-09-17 09:54 UTC
Labels: New Style
