### ISSUE TITLE
Customizable Test Chamber Sign

### ISSUE THREAD

**Issue by QuantiX999** [TeamSpen210/BEE2-items#897] opened 2016-10-05 13:02 UTC
The one at the beginning of each test chamber. It would be nice to customize it.

**Comment by LautaroL20** [comment] 2016-10-05 13:14
I don´t think this is doable, but it would be nice.

**Comment by TeamSpen210** [comment] 2016-10-05 23:08
Unfortunately you can't customise that sign, unless you do something like generate a custom texture for it or the like.

**Comment by Luke18033** [comment] 2016-10-06 03:45
This is a duplicate of #605 anyway.

**Closed by Luke18033** 2016-10-06 03:45 UTC
Labels: enhancement
