### ISSUE TITLE
Implement Thinking with Time machine style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1142] opened 2016-12-05 16:05 UTC
Implement the Thinking with Time machine style (long term)

it's creator has requested it get implemented since they made the PTI version in their game buggy and their PTI didn't use the new TWTM panels...

**Comment by TheDarkBomber** [comment] 2016-12-05 16:22
Duplicate of #589

**Closed** 2016-12-05 16:23 UTC
Labels: duplicate, New Style
