### ISSUE TITLE
Bug : Monitor is generating it's screen inside the monitors hole instead of on the monitor.

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#1136] opened 2016-12-04 17:23 UTC
![20161204092727_1](https://cloud.githubusercontent.com/assets/22718537/20867931/51cfdf62-ba04-11e6-9c5c-b22119ab558a.jpg)
![20161204092722_1](https://cloud.githubusercontent.com/assets/22718537/20867932/51d0ee0c-ba04-11e6-8ede-030f38e04e05.jpg)

**Comment by Byzarru** [comment] 2016-12-04 18:27
Duplicate of #1083.

**Closed** 2016-12-04 18:39 UTC
Labels: bug
