### ISSUE TITLE
Portal 1 exit door does not open when both player are next to it

### ISSUE THREAD

**Issue by TeamSpen210** [TeamSpen210/BEE2-items#480] opened 2016-04-16 09:35 UTC
_From @CrashingScience on April 15, 2016 14:25_

_Copied from original issue: BenVlodgi/BEE2.4#286_

**Comment by TeamSpen210** [comment] 2016-04-16 09:35
_From @Konclan on April 15, 2016 14:26_

Can we get a screenshot?

**Comment by TeamSpen210** [comment] 2016-04-16 09:35
_From @Konclan on April 15, 2016 14:28_

also it's a good idea to post anything related to items here https://github.com/TeamSpen210/BEE2-items

**Comment by TeamSpen210** [comment] 2016-04-16 09:35
_From @CrashingScience on April 16, 2016 9:28_

![20160416094735_1](https://cloud.githubusercontent.com/assets/16468734/14580204/ff60e566-03bd-11e6-9573-c3cc44bff30b.jpg)

**Comment by LautaroL20** [comment] 2016-04-16 15:41
This bug was also already reported by @xDadiKx some time ago:

"[BUG] P1 Exit Co-op door won't open" LINK: https://github.com/TeamSpen210/BEE2-items/issues/364

**Comment by LautaroL20** [comment] 2016-04-16 15:45
@TeamSpen210 - People make duplicated post because some reports does not got "Label", when you have the time, i recomend to label them. Here is some links to non-labels bug reports:

https://github.com/TeamSpen210/BEE2-items/issues/364
https://github.com/TeamSpen210/BEE2-items/issues/347
https://github.com/TeamSpen210/BEE2-items/issues/381
https://github.com/TeamSpen210/BEE2-items/issues/376
https://github.com/TeamSpen210/BEE2-items/issues/375
https://github.com/TeamSpen210/BEE2-items/issues/374
https://github.com/TeamSpen210/BEE2-items/issues/373
https://github.com/TeamSpen210/BEE2-items/issues/370

**Comment by LautaroL20** [comment] 2016-08-29 16:59
Duplicate of: #364

**Closed by LautaroL20** 2016-08-29 16:59 UTC
Labels: bug, duplicate, Portal 1
