### ISSUE TITLE
[New item] Breakble gel pipe.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#660] opened 2016-08-08 01:01 UTC
A pipe with gel flowing through that can be destroyed by bombs. Can be useful in maps with no gel droppers allowed with this being the only source of gel.

**Comment by TeamSpen210** [comment] 2016-08-08 04:16
This is more of a duplicate of #661, where it would behave like this when the tube is a gel tube. There'd be a 'gel tube' item placed at the start of the tube, which causes it to fill with gel and dispense the correct type from the end and midway when broken.

**Closed** 2016-08-08 04:17 UTC
Labels: duplicate, New Item
