### ISSUE TITLE
Prl20 Bug: Flip Panel is missing its "Black Metal Surface" when its placed on floor, into the Original Clean Style

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#516] opened 2016-05-02 09:29 UTC
![20160502061952_1](https://cloud.githubusercontent.com/assets/12244376/14951384/ea122198-102e-11e6-92ba-be5d056954bc.jpg)

**Comment by TeamSpen210** [comment] 2016-05-02 09:38
This is a duplicate of #512.

**Closed by TeamSpen210** 2016-05-02 09:38 UTC
Labels: bug, duplicate

**Comment by Luke18033** [comment] 2016-06-13 18:09
@TeamSpen210 This isn't a duplicate really, one is a ceiling and one is a flip panel.

**Comment by TheReviewers** [comment] 2016-06-13 18:24
@Luke18033 Same texture

**Comment by TeamSpen210** [comment] 2016-06-13 21:31
It is actually, they both read the same wrong config entry.
