### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: The "Draw Bridge" is "Unstyled"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#722] opened 2016-08-21 06:52 UTC
![20160821034639_1](https://cloud.githubusercontent.com/assets/12244376/17835793/a37218da-6752-11e6-8b67-6eb5e1877716.jpg)

**Comment by Luke18033** [comment] 2016-09-12 01:16
This is a duplicate of #535

**Closed by Luke18033** 2016-09-12 01:16 UTC
Labels: bug, Missing item variant, Overgrown
