### ISSUE TITLE
bottomless pit doesn't teleport player yet

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#401] opened 2016-03-16 16:22 UTC
@TeamSpen210 - bottomless pits don't teleport the player yet

this needs to be implemented with some form of overide to force the camera to turn and look down.

**Comment by LautaroL20** [comment] 2016-10-05 13:16
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/290

**Closed by LautaroL20** 2016-10-05 13:16 UTC
Labels: duplicate
