### ISSUE TITLE
Overgrown glass panel error

### ISSUE THREAD

**Issue by SPAHI4** [TeamSpen210/BEE2-items#1029] opened 2016-11-21 21:59 UTC
Overgrown styled glass panel error

With no connected items
![image](https://cloud.githubusercontent.com/assets/1670998/20502306/8fa145ac-b04e-11e6-9f4d-77b9b06b46f6.png)

With connected items map just don't compiling

**Comment by LautaroL20** [comment] 2016-11-21 22:11
This bug is fixed in next release, stay tunned ;)

This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/168

**Closed by LautaroL20** 2016-11-21 22:11 UTC
Labels: bug, duplicate, Fixed in next release, Overgrown
