### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style: Co-op Exit "Does not open" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#642] opened 2016-07-30 01:31 UTC
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/17267315/0ced189c-55dc-11e6-91f1-3b2e0896054c.gif)

**Comment by ZombiePwner1** [comment] 2016-08-01 04:57
There is a missing trigger most likely for the door to open when both bots are there.

**Comment by LautaroL20** [comment] 2016-08-01 21:46
Also, it is missing its "Tick Sound Effect" when you approach to the exit door. It is muted wich is another bug i should report too.

**Comment by TeamSpen210** [comment] 2016-08-20 03:06
Actually the bug was that the checkbox was inverted in behavior.

**Comment by ZombiePwner1** [comment] 2016-09-05 06:19
This is a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/364

**Closed** 2016-09-05 06:19 UTC
Labels: bug, duplicate, fixed, Portal 1
