### ISSUE TITLE
Portal 1 Correct Textures And Idea

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#416] opened 2016-03-19 04:05 UTC
So I Was Wondering When Will You Add The Correct Model To The 1500 Megawatt Aperture Science Heavy Duty Super Colliding Super Button.
The One That Shines When You Press On It.
Also In The Full Release, Will There Be The Choreo Box?

**Comment by TeamSpen210** [comment] 2016-03-19 04:33
The shining wouldn't be caused by the actual model, it's because of the position of the light entity. I don't think I'll be adding the choreo box back, it's not really going to work well for Caroline or the Announcer (They have so few lines there wouldn't be anything to match.)

**Comment by TheReviewers** [comment] 2016-03-19 16:28
What About P1 Glados? Will Her Voice Be Finally Added, Ive Been Waiting Too Long ;-;

**Comment by TheReviewers** [comment] 2016-03-19 16:38
XD I just realised There Is a voice line menu XD

**Comment by TeamSpen210** [comment] 2016-03-19 20:24
I won't be adding P1 GLaDOS. The problem is that there isn't a way to pack the files to match the user's language- I don't want to just use the English version everywhere.

**Comment by TheReviewers** [comment] 2016-03-20 14:13
Nope, You Added The Option To Add A p1 glados voice, You Will Add The Voicelines ;-; Please.
P1 Glados Is Love

**Closed** 2016-05-01 08:29 UTC
Labels: bug, fixed
