### ISSUE TITLE
Overgrown: exit corridors 1, 2 and 4 causing compile error

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#1110] opened 2016-12-01 21:22 UTC
I did a quick search and couldn't see this glaring issue reported. A Steam contact wanted me to check if I got the same error, and I do. Whenever I compile an Overgrown map, no matter what's in it, it could be a brand new, clean chamber, if I have exits 1, 2 or 4 selected, I get this error:

```
[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/4 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3044, misses=305, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'rexcubepelletfizzle': False, 'allowgoomist': True, 'fixfizzlerbump': False, 'bee2_goo_debris': True, 'bee_show_trigger': False, 'unlockdefault': False, 'nomidvoices': False, 'multiversecave': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/walkway_destroyed_64a.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "c:\Program Files (x86)\BeeMod\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)
```

Corridor 3, Floor BTS, works. Sensibly enough, as the stairs aren't in that one...

**Comment by Luke18033** [comment] 2016-12-01 21:52
Duplicate of #1040

**Closed by Luke18033** 2016-12-01 21:52 UTC
