### ISSUE TITLE
[BUG] Portal 1 Angled Panels Dont Work

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#417] opened 2016-03-19 19:35 UTC
So Basically , If You Try To Connect Any Button Or Catcher Or Anything to Move A Panel, It Gets a Build error ;-; halp

**Comment by ZombiePwner1** [comment] 2016-07-21 03:37
This is still going around in prl 21.5 It will be fixed in the next update.

**Comment by LautaroL20** [comment] 2016-07-30 16:00
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/414

**Closed by LautaroL20** 2016-07-30 16:00 UTC
Labels: bug, duplicate, fixed
