### ISSUE TITLE
[Bug] monitor screen is missing icon in the editor.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#784] opened 2016-09-10 08:11 UTC
![20160910161106_1](https://cloud.githubusercontent.com/assets/18079316/18409000/3ee80eae-7771-11e6-9fcc-0e8691c6d541.jpg)

**Comment by TeamSpen210** [comment] 2016-09-10 08:15
Duplicate of #782.

**Closed by TeamSpen210** 2016-09-10 08:15 UTC
Labels: bug, duplicate

**Comment by ZombiePwner1** [comment] 2016-09-12 03:14
How did this one get created? I must have mixed them up.
