### ISSUE TITLE
[PRL 22 Bug] Visible nodraw in coop disassembly room.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#922] opened 2016-10-15 09:12 UTC
![20161015170407_1](https://cloud.githubusercontent.com/assets/18079316/19408900/6cd6e804-92fa-11e6-9567-382db732b89b.jpg)

**Comment by Luke18033** [comment] 2016-10-15 15:06
Duplicate of #906.

**Closed by Luke18033** 2016-10-15 15:06 UTC
Labels: bug, Clean, visual bug
