### ISSUE TITLE
BTS Faith Plate Target turns into white texture

### ISSUE THREAD

**Issue by corrupt21** [TeamSpen210/BEE2-items#830] opened 2016-09-16 03:46 UTC
![20160916134435_1](https://cloud.githubusercontent.com/assets/17777059/18574808/ec04b064-7c13-11e6-89e7-fd16e0e00978.jpg)

**Comment by ZombiePwner1** [comment] 2016-09-16 03:51
This is a duplicate of another issue.

**Comment by LautaroL20** [comment] 2016-09-16 03:53
Yep: https://github.com/TeamSpen210/BEE2-items/issues/346

**Closed** 2016-09-16 03:52 UTC
Labels: duplicate

**Comment by LautaroL20** [comment] 2016-09-16 03:55
This is probably the most duplicatest bug report ever. I remember showing at least 4 duplications from this same bug, with this one is the 5th time :)

**Comment by ZombiePwner1** [comment] 2016-09-16 03:55
It seems that there is a custom BTS target texture that isn't packing.

**Comment by LautaroL20** [comment] 2016-09-16 04:01
@ZombiePwner1 - the same goes for the the 80´s Old Aperture: Piston Platform "Textures" are not being packed for people who do not have Bee2.4 Installed:

![20160819010057_1](https://cloud.githubusercontent.com/assets/12244376/17798607/20acc954-65a9-11e6-87cc-ae67730c65e1.jpg)
