### ISSUE TITLE
[Bug] Futbol spawner spawns 7 or 8 futbols when auto respawn is enabled.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#697] opened 2016-08-16 01:06 UTC
Yes ik the bug with the spawner is already crazy but if u look closely it spawns around 7 or 8 futbols at once

**Comment by LautaroL20** [comment] 2016-08-16 01:10
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/603

**Closed by LautaroL20** 2016-08-16 01:10 UTC
Labels: bug, duplicate
