### ISSUE TITLE
[Bug] Overgrown laser relays causes a compile error.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#763] opened 2016-09-04 08:47 UTC
] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\GameInfo.txt
 | GameInfo, FileSystem, SearchPaths, 
 | Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/items/laser/relay_center_com_var1.vmf
 | 
 |_

[I] BEE2_config: Saving changes in config "C:\Users\Josh\Desktop\File folder\PR 21\config/compile.cfg"!
[E] vbsp: VBSP failed! (1)

**Comment by LautaroL20** [comment] 2016-09-04 15:56
TeamSpen210 gently gave me his fixed compiler since a month ago, and this got fixed. Also this is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/611

**Closed** 2016-09-04 15:56 UTC
Labels: bug, duplicate, fixed, Overgrown
