### ISSUE TITLE
[Bug] BTS where is the coop exit door?

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#811] opened 2016-09-12 11:04 UTC
![20160912190312_1](https://cloud.githubusercontent.com/assets/18079316/18433680/a6381d28-791b-11e6-9bd4-fef558069a74.jpg)

**Comment by LautaroL20** [comment] 2016-09-12 11:08
Duplicate of "Co-op Exit gets "Areaportal leaks", is "Out of Control" and its "Unstyled" (https://github.com/TeamSpen210/BEE2-items/issues/341)

**Closed** 2016-09-12 11:09 UTC
Labels: BTS, bug, duplicate
