### ISSUE TITLE
Missing clear panel instance

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#964] opened 2016-10-29 15:16 UTC
Hooking a button to a clear panel in overgrown style resulted in a build error with this message
 | Could not open instance file instances/BEE2/over/items/panel_clear.vmf

**Comment by LautaroL20** [comment] 2016-10-29 16:26
That bug seriously is older than my great grandparents, im surprised how it wasn´t fixed yet.....

Duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/168

**Closed** 2016-10-29 16:26 UTC
Labels: bug, duplicate, Overgrown
