### ISSUE TITLE
[Enhancement] Add Portal Stories Mel Music in a Separated Standalone Package.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#685] opened 2016-08-11 03:50 UTC
Add Portal Stories Mel Music on a Separated Standalone Package.

**Comment by LautaroL20** [comment] 2016-08-11 03:52
Aperture tag music also should be added.

**Comment by ZombiePwner1** [comment] 2016-08-11 03:55
Aperture tag music already is added.

**Comment by LautaroL20** [comment] 2016-08-11 03:57
Well, for some reason beemod does not want to pack it on builded maps.

**Comment by ZombiePwner1** [comment] 2016-08-11 03:58
That's because it's not packed into P2 yet it's only packed for aperture tag.

**Comment by ZombiePwner1** [comment] 2016-08-11 03:59
https://github.com/TeamSpen210/BEE2-items/issues/666

**Comment by ZombiePwner1** [comment] 2016-08-11 04:04
I've got the music working because i'm loading aperture tag's music through portal 2's GameInfo.txt

**Comment by SpyyZ158** [comment] 2016-08-11 22:56
duplicate of https://github.com/BenVlodgi/BEE2.4/issues/292

**Comment by LautaroL20** [comment] 2016-08-12 03:23
@SpyyZ158 True.

**Closed** 2016-11-23 17:57 UTC
Labels: enhancement, Fixed in next release
