### ISSUE TITLE
bug: lifts, piston platforms do not generate pillar in pit if placed in bottomless pit

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1122] opened 2016-12-02 15:00 UTC
lifts, piston platforms do not generate a pillar in the skybox part of the pit if placed in a bottomless pit...

**Comment by Luke18033** [comment] 2016-12-02 17:47
Duplicate of... something. I'll do a quick search.

**Closed by Luke18033** 2016-12-02 17:47 UTC
