### ISSUE TITLE
[Bug] Portal 1 style uses portal 2 camera on large observation room instead of P1 cameras.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#686] opened 2016-08-11 03:53 UTC

**Comment by TeamSpen210** [comment] 2016-08-11 05:22
Duplicate of #683.

**Closed by TeamSpen210** 2016-08-11 05:22 UTC
Labels: bug, Portal 1

**Comment by TheDarkBomber** [comment] 2016-08-11 10:28
This isn't a duplicate of #683 because that issue is about a "mysterious thing" next to the security camera, and this issue is about using Portal 2 security cameras next to the large observation room in Portal 1 style.

**Comment by TeamSpen210** [comment] 2016-08-11 10:30
No, they're both because the P1 camera isn't packing.

**Comment by TheDarkBomber** [comment] 2016-08-11 19:36
This would make more sense to be a semi-duplicate or something.
