### ISSUE TITLE
pneumatic tubes with debris animation or cube outside the chamber

### ISSUE THREAD

**Issue by I-love-bee-2** [TeamSpen210/BEE2-items#1195] opened 2016-12-13 16:45 UTC
In some maps the official campaign of the pipe used to transport bombs by pressing a button. This is a good way to move the interactive elements of the game behind the scenes, as usual distributors cubes do not fit in this topic

**Comment by Luke18033** [comment] 2016-12-13 21:22
What?

**Comment by TeamSpen210** [comment] 2016-12-13 21:29
This is a duplicate of #662.

**Closed** 2016-12-13 21:30 UTC
Labels: duplicate, enhancement, Suggestion
