### ISSUE TITLE
[Bug] Cubes don't get destroyed when hit by an energy pellet.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#664] opened 2016-08-08 08:43 UTC
Cubes don't get destroyed by energy pellets even if the option for pellets to destroy cubes is ticked.

**Comment by LautaroL20** [comment] 2016-08-08 23:58
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/567

**Comment by TeamSpen210** [comment] 2016-08-09 00:18
That's the issue for originally adding it, this is a bug with inheriting the configuration in styles (like Original Clean or 1970s).

**Comment by ZombiePwner1** [comment] 2016-08-09 00:56
What other styles does this affect? Clean label is for original clean.

**Comment by TeamSpen210** [comment] 2016-08-09 07:01
All styles inheriting from another, so Clean Original, 60s, 70s and 80s.

**Comment by BenVlodgi** [comment] 2016-08-09 13:58
A little unrelated, but are the energy balls that destroy cubes a different color?
I think they should be.
The ball should be red or something if it is going to kill cubes, as that is not a normal feature of energy pellets in vanilla Portal.

**Comment by TeamSpen210** [comment] 2016-08-09 19:03
They aren't. That would conflict with infinite-lifetime pellets though, which are green. Really you'll only experience the behaviour if you try bouncing pellets off cubes, or use cube holders.

**Comment by BenVlodgi** [comment] 2016-08-12 19:40
Bouncing pellets off cubes is a mechanic used in Portal 1, the cube doesn't dissolve when that happens.
They aren't an item that is used that often, so most people probably won't notice.
I do still think there should be something done to distinguish pellets that will kill cubes. Perhaps an additional particle effect parented to the projectile?

**Comment by TeamSpen210** [comment] 2016-08-12 21:32
It's a global option, so all pellets will dissolve cubes if enabled. There might be a nice particle to parent, but Overgrown Style pellets actually have additional particles already.

**Closed** 2016-09-10 03:40 UTC
Labels: bug, Clean, fixed, Retro
