### ISSUE TITLE
Bts Gel Crashes Game

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#498] opened 2016-04-25 07:22 UTC
When activating gel, it crashes the game

**Comment by Konclan** [comment] 2016-04-25 11:19
Is there a crash report?

**Comment by TheReviewers** [comment] 2016-04-25 11:58
@Konclan How can i see the console when the game crashes (shuts down)

**Comment by Konclan** [comment] 2016-04-25 12:25
There is usually a crash report text file generated in the portal 2 folder somewhere

**Comment by LautaroL20** [comment] 2016-04-25 19:18
Ive already reported this bug long time ago: https://github.com/TeamSpen210/BEE2-items/issues/347

**Comment by TheReviewers** [comment] 2016-04-25 19:29
@LautaroL20 you said reflection, but it happens on all

**Comment by LautaroL20** [comment] 2016-04-25 21:10
@TheReviewers - It is not my case, i tested all the gel droppers but it only crashes with "Reflection Gel".

**Comment by LautaroL20** [comment] 2016-08-29 17:40
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/347

**Closed by LautaroL20** 2016-08-29 17:40 UTC
Labels: bug, crash, duplicate
