### ISSUE TITLE
Bug angled panel

### ISSUE THREAD

**Issue by Stendec-UA** [TeamSpen210/BEE2-items#414] opened 2016-03-18 10:42 UTC
Domkrat S/N unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF G:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 61 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr19 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "G:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "G:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: True
[I] cond.core: Checking Conditions...
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.catwalks: Starting catwalk generator...
[I] cond.core: Exiting empty condition!
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[W] cond.core: Debug: checking-door = <Entity>: 
 | {
 | 	 origin = "832 704 64"
 | 	 angles = "-90 90 0"
 | 	 targetname = "doorexit2"
 | 	 classname = "func_instance"
 | 	 file = "instances/BEE2/p1/elevator_sp/door_frame_black.vmf"
 | }
 |_

[W] cond.core: Debug: norm_nodoor
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: ['quote_loc', 'base', 'quoteevents', 'coopresponses', 'midchamber', 'group', 'group']
[I] voiceLine: Generating responses data..
[W] BEE2_config: Config "bee2\resp_voice.cfg" not found! Using defaults...
[I] voiceLine: Chosen: Property('Line', [Property('Name', 'Federal Regulations'), Property('ID', 'GENERIC_1'), Property('Trans', 'Federal regulations require me to warn you that this next test chamber... is looking pretty good.'), Property('choreo', 'scenes/npc/glados/a2_triple_laser01.vcd')])
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"Name" "Federal Regulations"
 | 	"ID" "GENERIC_1"
 | 	"Trans" "Federal regulations require me to warn you that this next test chamber... is looking pretty good."
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Waddle Over To The Elevator'), Property('ID', 'GENERIC_1'), Property('Trans', "Waddle over to the elevator and we'll continue the testing."), Property('Choreo', 'scenes/npc/glados/testchambermisc12.vcd')])
 | Property('Line_SP', [Property('Name', 'Mildly Impressive'), Property('ID', 'GENERIC_2'), Property('Trans', 'That was genuinely mildly impressive.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard01.vcd')])
 | Property('Line_SP', [Property('Name', 'Statistically Speaking...'), Property('ID', 'GENERIC_3'), Property('Trans', 'You are playing above the global average. Statistically speaking, there are actually people playing worse than you.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard20.vcd')])
 | Property('Line_SP', [Property('Name', 'Very Not Completely Bad'), Property('ID', 'GENERIC_4'), Property('Trans', 'Very not completely bad.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard23.vcd')])
 | Property('Line_SP', [Property('Name', 'Maybe I Was Wrong'), Property('ID', 'GENERIC_5'), Property('Trans', '[impressed] Maybe I was wrong about you.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard07.vcd')])
 | Property('Line_SP', [Property('Name', 'Impressive'), Property('Trans', 'Impressive.'), Property('ID', 'GENERIC_6'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard06.vcd')])
 |_Property('Line_SP', [Property('Name', 'Congratulations'), Property('Trans', 'Congratulations.'), Property('ID', 'GENERIC_7'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard03.vcd')])

[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"Name" "Maybe I Was Wrong"
 | 	"ID" "GENERIC_5"
 | 	"Trans" "[impressed] Maybe I was wrong about you."
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard07.vcd"
 | 	}
 |_

[I] voiceLine: Mid quotes: []
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: 
[I] cond.core: Style Vars:
[I] cond.core: Global instances: 
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Adding Goo Mist...
[I] vbsp: Done!
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "#scripts/bee2_snd/p1_pgun_sounds.txt"
[I] vbsp: "#scripts/bee2_snd/portal_sounds.txt"
[I] vbsp: "-#scripts/game_sounds_player_portal2.txt"
[I] vbsp: "-#scripts/game_sounds_weapons_portal.txt"
[I] vbsp: "materials/BEE2/ind_p1/corner_floor.vmt"
[I] vbsp: "materials/BEE2/ind_p1/corner_wall.vmt"
[I] vbsp: "materials/BEE2/ind_p1/p1_antline_floor_double.vtf"
[I] vbsp: "materials/BEE2/ind_p1/p1_antline_wall_double.vtf"
[I] vbsp: "materials/BEE2/ind_p1/straight_floor.vmt"
[I] vbsp: "materials/BEE2/ind_p1/straight_wall.vmt"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun.vmt"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun.vtf"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_blue.vmt"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_blue.vtf"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_exponent.vtf"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_glass.vmt"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_glass.vtf"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_normal.vtf"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_orange.vmt"
[I] vbsp: "materials/BEE2/models/p1_pgun/v_portalgun_orange.vtf"
[I] vbsp: "materials/BEE2/models/props_p1/walllight_sheet.vmt"
[I] vbsp: "materials/BEE2/models/props_p1/walllight_sheet.vtf"
[I] vbsp: "materials/BEE2/p1/light_recessedcool_glow.vmt"
[I] vbsp: "materials/BEE2/p1/metalwall048b_lrg.vmt"
[I] vbsp: "materials/BEE2/p1/metalwall048b_lrg.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_lrg_dx8.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_lrg_normal.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_med.vmt"
[I] vbsp: "materials/BEE2/p1/metalwall048b_med.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_med_dx8.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[I] vbsp: "materials/BEE2/p1/metalwall048b_med_normal.vtf"
[I] vbsp: "materials/BEE2/p1/modular_wall_light.vmt"
[I] vbsp: "materials/BEE2/p1/obs/detail_concrete_03.vtf"
[I] vbsp: "materials/BEE2/p1/obs/metaldoor028a.vmt"
[I] vbsp: "materials/BEE2/p1/obs/metaldoor028a.vtf"
[I] vbsp: "materials/BEE2/p1/obs/observation_tilefloor001a.vmt"
[I] vbsp: "materials/BEE2/p1/obs/observation_tilefloor001a.vtf"
[I] vbsp: "materials/BEE2/p1/obs/observationwall_001a.vmt"
[I] vbsp: "materials/BEE2/p1/obs/observationwall_001a.vtf"
[I] vbsp: "materials/BEE2/p1/obs/observationwall_001a_normal.vtf"
[I] vbsp: "materials/BEE2/p1/obs/observationwall_001b.vmt"
[I] vbsp: "materials/BEE2/p1/obs/observationwall_001b.vtf"
[I] vbsp: "materials/BEE2/p1/obs/observationwall_001b_height-ssbump.vtf"
[I] vbsp: "materials/BEE2/p1/overlay_light_gradient.vtf"
[I] vbsp: "models/BEE2/p1_pgun.dx90.vtx"
[I] vbsp: "models/BEE2/p1_pgun.mdl"
[I] vbsp: "models/BEE2/p1_pgun.vvd"
[I] vbsp: "models/BEE2/props_p1/door_frame_thick.dx90.vtx"
[I] vbsp: "models/BEE2/props_p1/door_frame_thick.mdl"
[I] vbsp: "models/BEE2/props_p1/door_frame_thick.phy"
[I] vbsp: "models/BEE2/props_p1/door_frame_thick.vvd"
[I] vbsp: "models/BEE2/props_p1/floor_button_base.dx90.vtx"
[I] vbsp: "models/BEE2/props_p1/floor_button_base.mdl"
[I] vbsp: "models/BEE2/props_p1/floor_button_base.phy"
[I] vbsp: "models/BEE2/props_p1/floor_button_base.vvd"
[I] vbsp: "models/BEE2/props_p1/floor_button_just_top.dx90.vtx"
[I] vbsp: "models/BEE2/props_p1/floor_button_just_top.mdl"
[I] vbsp: "models/BEE2/props_p1/floor_button_just_top.phy"
[I] vbsp: "models/BEE2/props_p1/floor_button_just_top.vvd"
[I] vbsp: "models/BEE2/props_p1/obs_light.dx90.vtx"
[I] vbsp: "models/BEE2/props_p1/obs_light.mdl"
[I] vbsp: "models/BEE2/props_p1/obs_light.phy"
[I] vbsp: "models/BEE2/props_p1/obs_light.vvd"
[I] vbsp: "models/BEE2/props_p1/security_camera.dx80.vtx"
[I] vbsp: "models/BEE2/props_p1/security_camera.dx90.vtx"
[I] vbsp: "models/BEE2/props_p1/security_camera.mdl"
[I] vbsp: "models/BEE2/props_p1/security_camera.phy"
[I] vbsp: "models/BEE2/props_p1/security_camera.sw.vtx"
[I] vbsp: "models/BEE2/props_p1/security_camera.vvd"
[I] vbsp: "scripts/vscripts/BEE2/change_model.nut"
[I] vbsp: "scripts/vscripts/BEE2/set_p1_pgun.nut"
[I] vbsp: "sound/BEE2/p1/garage_stop1.wav"
[I] vbsp: "sound/BEE2/p1/pgun/ambient.wav"
[I] vbsp: "sound/BEE2/p1/pgun/portal_enter1.wav"
[I] vbsp: "sound/BEE2/p1/pgun/portal_enter2.wav"
[I] vbsp: "sound/BEE2/p1/pgun/portal_exit1.wav"
[I] vbsp: "sound/BEE2/p1/pgun/portal_exit2.wav"
[I] vbsp: "sound/BEE2/p1/wall_move5.wav"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
Calling original VBSP...
"G:\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "G:/Steam/steamapps/common/Portal 2/portal2/" "G:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2015)
4 threads
materialPath: G:\Steam\steamapps\common\Portal 2\portal2\materials
Loading G:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/p1/items/panel_angled.vmf

VBSP failed! (1)

**Comment by Stendec-UA** [comment] 2016-03-18 10:43
- 

- [ ] @ #[1. ](`

> **_**url**_**

`)

**Comment by Stendec-UA** [comment] 2016-03-18 10:44
![20160318123306_1](https://cloud.githubusercontent.com/assets/14983383/13875536/14dbb90c-ed07-11e5-8d4a-d40e1f73c821.jpg)

**Comment by TheReviewers** [comment] 2016-03-19 04:18
Its Not Just The Panel , Its The Stairs And Victory Lifts, And Others :3

**Comment by harritron2k2** [comment] 2016-03-20 14:57
Also the panel doesn't have any editor models if you set the angles to 30, 45, or 60 degrees

**Comment by Luke18033** [comment] 2016-07-27 01:17
@Stendec-UA The BEE2 currently does not support connecting inputs to angled panels in Portal 1.

**Comment by TeamSpen210** [comment] 2016-07-27 03:50
This will be fixed in the next release.

**Comment by LautaroL20** [comment] 2016-08-12 08:37
Issue was fixed.

**Comment by LautaroL20** [comment] 2016-08-29 15:32
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/120

**Closed by LautaroL20** 2016-08-29 15:32 UTC
Labels: bug, duplicate, fixed
