### ISSUE TITLE
Missing Item Icons

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#564] opened 2016-05-11 20:05 UTC
Several items have a missing icon in-game. The broken items seen in the screenshot are: Compressed Smoke Field, Force Deflection Field, Paint Fizzler, and all three vactubes.
![20160511125634_1](https://cloud.githubusercontent.com/assets/19228201/15194483/f1c0d40c-1777-11e6-9c1a-4e64078ae091.jpg)
Speaking of vactubes, they will not compile in my map even when I connect them in the order I want them to travel. I have messed around with the connections and rotation handles but have gotten no different results.

**Comment by Konclan** [comment] 2016-05-11 20:27
They are kinda confusing at first, but once you understand how they work, it's pretty simple. I can get a screenshot of a vactube system that works if you need.

**Comment by Luke18033** [comment] 2016-05-11 20:32
@Konclan Yes, I'd like a screenshot.

**Comment by TeamSpen210** [comment] 2016-05-12 02:31
It'll probably help having proper editor models for them as well.

**Comment by Luke18033** [comment] 2016-05-12 17:16
The vactubes have missing icons too.

**Comment by Luke18033** [comment] 2016-05-12 18:37
@Konclan Also, can vactubes carry the player?

**Comment by TheReviewers** [comment] 2016-05-12 19:22
@Luke18033 Yes They Can :D

**Comment by Luke18033** [comment] 2016-05-12 21:05
@TeamSpen210 This is original clean style, not regular clean.

**Comment by Luke18033** [comment] 2016-05-12 21:44
@TheReviewers Another thing, do you need to connect vactubes to PDV?

**Comment by TeamSpen210** [comment] 2016-05-12 23:35
The two items are totally unrelated. I'll eventually want to make a suction item and cube-destroying item, which together form the diversity vent.

**Comment by Luke18033** [comment] 2016-05-24 21:08
@Konclan So...the screenshot?

**Comment by BenVlodgi** [comment] 2016-05-25 20:03
For the BEEMOD items, I would make the icon by placing the editor model in a white room (probably a projected texture too)
Have the camera at a fixed angle, so all my icons would have the same perspective, I think I did have to change some of them though.

**Comment by TeamSpen210** [comment] 2016-05-25 21:00
I do that too, I have s room I made with a point_viewcontrol on some movelinears to allow panning the camera. If it's just got 1 model, I usually just screenshot the Model Viewer (with the correct blue background).

**Comment by Luke18033** [comment] 2016-07-27 18:15
## More Missing Icons!

I have found more missing icons! The missing icons are: 60's Small Observation Grate, Locked Pedestal Button and Paint Fizzler (which I reported before).
![20160514105746_1](https://cloud.githubusercontent.com/assets/19228201/15269946/ad091df8-19c3-11e6-8aec-a1a723018499.jpg)
Unfortunately, I can't seem to compile any 60's tests (#571) so I don't know how these look ingame.

**Comment by LautaroL20** [comment] 2016-08-29 15:38
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/302

**Closed by LautaroL20** 2016-08-29 15:38 UTC
Labels: bug, Clean, duplicate

**Comment by Luke18033** [comment] 2016-12-28 01:26
@LautaroL20 No. That is models, this is icons. But these have probably been fixed now anyway.

**Comment by LautaroL20** [comment] 2017-02-07 12:28
@Luke18033 - True. Anyways all of these missing icons are fixed now.
